export function legalDocuments(profile: Record<string, any>, associationName: string) {
  const en = profile.language === 'en';
  const name = profile.legalName || associationName;
  const details = [
    `${en ? 'Website publisher' : 'Éditeur du site'} : ${name}`,
    profile.registrationNumber ? `${en ? 'Registration number' : 'Numéro d’enregistrement'} : ${profile.registrationNumber}` : '',
    profile.legalAddress ? `${en ? 'Registered office' : 'Siège social'} : ${profile.legalAddress}` : '',
    profile.email ? `${en ? 'Contact' : 'Contact'} : ${profile.email}` : '',
    profile.phone ? `${en ? 'Phone' : 'Téléphone'} : ${profile.phone}` : '',
    profile.publicationDirector ? `${en ? 'Publication manager' : 'Responsable de publication'} : ${profile.publicationDirector}` : '',
  ].filter(Boolean).join('\n\n');
  const cgv = en
    ? `GENERAL TERMS OF USE AND DONATIONS\n\n1. PURPOSE\nThese terms govern access to the website of ${name}, use of its information and contact services, and any donations or payments made through it. By using these services, the visitor accepts these terms.\n\n2. ASSOCIATION DETAILS\n${details}\n\n3. WEBSITE ACCESS\nThe association endeavours to keep the website accessible and accurate but cannot guarantee uninterrupted availability. It may update, suspend or remove content when necessary.\n\n4. DONATIONS AND PAYMENTS\nA donation is a voluntary contribution supporting the association’s mission and does not constitute the purchase of a product or service. The amount and payment details are confirmed before validation. Payment is processed by the payment provider shown during checkout. Any tax benefit depends on the donor’s situation and applicable law.\n\n5. CANCELLATION AND REFUNDS\nA completed donation is generally final. A donor who made a material error or suspects fraud should contact the association promptly. Any refund remains subject to applicable law and the association’s verification.\n\n6. PERSONAL DATA\nInformation submitted through forms is used to answer requests, administer donations and operate the association. It is retained only as long as necessary. Individuals may request access, correction or deletion using the contact details above, subject to legal retention duties.\n\n7. INTELLECTUAL PROPERTY\nTexts, photographs, logos, graphics and other website materials remain the property of their respective owners. Reproduction, distribution or commercial reuse without permission is prohibited.\n\n8. LIABILITY\nThe association is not liable for indirect loss, external websites, or interruptions beyond its reasonable control. Visitors remain responsible for the accuracy of information they submit.\n\n9. APPLICABLE LAW AND DISPUTES\nThese terms are governed by the law applicable to the association. The parties will first seek an amicable solution. If no agreement is reached, the competent courts will be determined under applicable procedural rules.\n\n10. CHANGES\nThe association may update these terms. The version published on the website is the applicable version.\n\nLast updated: ${new Date().toLocaleDateString('en-GB')}.`
    : `CONDITIONS GÉNÉRALES D’UTILISATION ET DE DONS\n\n1. OBJET\nLes présentes conditions encadrent l’accès au site de ${name}, l’utilisation de ses informations et formulaires, ainsi que les dons ou paiements éventuellement réalisés. L’utilisation du site implique leur acceptation.\n\n2. IDENTITÉ DE L’ASSOCIATION\n${details}\n\n3. ACCÈS AU SITE\nL’association s’efforce de maintenir le site accessible et ses informations à jour, sans garantir une disponibilité continue. Elle peut corriger, suspendre ou retirer un contenu lorsque cela est nécessaire.\n\n4. DONS ET PAIEMENTS\nLe don est une contribution volontaire destinée à soutenir la mission de l’association ; il ne constitue pas l’achat d’un produit ou d’un service. Le montant et les informations essentielles sont présentés avant validation. Le paiement est traité par le prestataire indiqué lors du règlement. L’éligibilité à un avantage fiscal dépend de la situation du donateur et de la réglementation applicable.\n\n5. ANNULATION ET REMBOURSEMENT\nUn don validé est en principe définitif. En cas d’erreur matérielle ou de suspicion de fraude, le donateur doit contacter rapidement l’association. Tout remboursement éventuel est étudié au regard des circonstances et des règles applicables.\n\n6. DONNÉES PERSONNELLES\nLes informations transmises servent à répondre aux demandes, gérer les dons et assurer le fonctionnement de l’association. Elles sont conservées pendant la durée nécessaire. Toute personne peut demander l’accès, la rectification ou l’effacement de ses données grâce aux coordonnées ci-dessus, sous réserve des obligations légales de conservation.\n\n7. PROPRIÉTÉ INTELLECTUELLE\nLes textes, photographies, logos, éléments graphiques et autres contenus restent la propriété de leurs titulaires. Toute reproduction, diffusion ou exploitation commerciale sans autorisation est interdite.\n\n8. RESPONSABILITÉ\nL’association ne peut être tenue responsable des dommages indirects, du contenu de sites externes ou d’une interruption indépendante de sa volonté. Chaque utilisateur reste responsable de l’exactitude des informations qu’il transmet.\n\n9. DROIT APPLICABLE ET LITIGES\nLes présentes conditions sont soumises au droit applicable à l’association. Les parties rechercheront d’abord une solution amiable. À défaut, la juridiction compétente sera déterminée selon les règles de procédure applicables.\n\n10. MODIFICATION DES CONDITIONS\nL’association peut mettre à jour ces conditions. La version publiée sur le site est la version applicable.\n\nDernière mise à jour : ${new Date().toLocaleDateString('fr-FR')}.`;
  return { details, cgv };
}
