'use client';
import { useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, ChevronDown, PackageCheck, Save, Search, Truck } from 'lucide-react';
import { PageHeader } from '@/components/ui';

type Item = { id: string; name: string; priceCents: number; quantity: number };
type Event = { id: string; title: string; detail: string; createdAt: string; visibleToCustomer: boolean };
type Order = { id: string; orderNumber: string; status: string; paymentStatus: string; fulfillmentStatus: string; deliveryStatus: string; customerName: string; customerEmail: string; customerPhone: string; shippingAddress: string; shippingLine1: string; shippingLine2: string; shippingPostalCode: string; shippingCity: string; shippingCountryCode: string; shippingMethod: string; shippingCents: number; subtotalCents: number; totalCents: number; carrier: string; trackingNumber: string; trackingUrl: string; internalNote: string; customerNote: string; createdAt: string; items: Item[]; events: Event[] };
const fulfilments = [['UNFULFILLED','À préparer'],['PREPARING','En préparation'],['ON_HOLD','En attente'],['FULFILLED','Préparée'],['CANCELLED','Annulée']];
const deliveries = [['NOT_SHIPPED','Non expédiée'],['READY_TO_SHIP','Prête à expédier'],['IN_TRANSIT','Expédiée / en transit'],['OUT_FOR_DELIVERY','En cours de livraison'],['DELIVERED','Livrée'],['DELIVERY_FAILED','Échec de livraison'],['CANCELLED','Annulée']];
const money = (n: number) => new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format((n||0)/100);
const date = (v: string) => new Date(v).toLocaleString('fr-FR',{dateStyle:'medium',timeStyle:'short'});

export function LogisticsClient({ initial, canEdit }: { initial: Order[]; canEdit: boolean }) {
  const [orders,setOrders]=useState(initial); const [q,setQ]=useState(''); const [filter,setFilter]=useState('ACTIVE'); const [open,setOpen]=useState<string|null>(null); const [saving,setSaving]=useState<string|null>(null);
  const list=useMemo(()=>orders.filter(o=>{const text=`${o.orderNumber} ${o.customerName} ${o.customerEmail} ${o.trackingNumber}`.toLowerCase(); if(q&&!text.includes(q.toLowerCase()))return false; if(filter==='ATTENTION')return o.paymentStatus==='PAID'&&!o.trackingNumber&&!['DELIVERED','CANCELLED'].includes(o.deliveryStatus); if(filter==='SHIPPED')return ['IN_TRANSIT','OUT_FOR_DELIVERY','DELIVERED'].includes(o.deliveryStatus); if(filter==='ACTIVE')return !['DELIVERED','CANCELLED'].includes(o.deliveryStatus); return true;}),[orders,q,filter]);
  const update=(id:string,patch:Partial<Order>)=>setOrders(a=>a.map(o=>o.id===id?{...o,...patch}:o));
  async function save(o:Order){setSaving(o.id);const r=await fetch(`/api/shop/orders/${o.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(o)});const d=await r.json().catch(()=>({}));setSaving(null);if(!r.ok){alert(d.error||'Enregistrement impossible.');return;}setOrders(a=>a.map(x=>x.id===o.id?{...x,...d.order,events:d.order.events||x.events}:x));}
  const paid=orders.filter(o=>o.paymentStatus==='PAID').length, attention=orders.filter(o=>o.paymentStatus==='PAID'&&!o.trackingNumber&&!['DELIVERED','CANCELLED'].includes(o.deliveryStatus)).length, shipped=orders.filter(o=>['IN_TRANSIT','OUT_FOR_DELIVERY'].includes(o.deliveryStatus)).length;
  return <div><PageHeader title="Commandes & logistique" subtitle="Préparation, expédition, suivi client et historique centralisés." />
    <div className="mb-5 grid gap-3 sm:grid-cols-3"><Stat icon={<PackageCheck/>} label="Commandes payées" value={paid}/><Stat icon={<AlertTriangle/>} label="Suivi à compléter" value={attention} warn/><Stat icon={<Truck/>} label="En transit" value={shipped}/></div>
    <div className="mb-4 flex flex-wrap gap-2"><div className="relative min-w-60 flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-gray-400"/><input className="input pl-9" value={q} onChange={e=>setQ(e.target.value)} placeholder="Commande, client, email, suivi…"/></div><select className="input w-auto" value={filter} onChange={e=>setFilter(e.target.value)}><option value="ACTIVE">À traiter</option><option value="ATTENTION">Suivi manquant</option><option value="SHIPPED">Expédiées</option><option value="ALL">Toutes</option></select></div>
    <div className="space-y-3">{list.map(o=>{const warn=o.paymentStatus==='PAID'&&!o.trackingNumber&&!['DELIVERED','CANCELLED'].includes(o.deliveryStatus);const good=!!o.trackingNumber&&['IN_TRANSIT','OUT_FOR_DELIVERY','DELIVERED'].includes(o.deliveryStatus);return <article key={o.id} className="rounded-2xl bg-white shadow-sm ring-1 ring-gray-200"><button className="flex w-full flex-wrap items-center gap-3 p-4 text-left" onClick={()=>setOpen(open===o.id?null:o.id)}><div className={`grid h-10 w-10 place-items-center rounded-xl ${good?'bg-green-100 text-green-700':warn?'bg-red-100 text-red-700':'bg-blue-50 text-blue-700'}`}>{good?<CheckCircle2/>:warn?<AlertTriangle/>:<Truck/>}</div><div className="min-w-48 flex-1"><p className="font-extrabold text-gray-900">#{o.orderNumber.slice(-10).toUpperCase()} · {o.customerName||'Client'}</p><p className="text-sm text-gray-500">{o.items.map(i=>`${i.quantity}× ${i.name}`).join(', ')}</p></div><div><p className="font-extrabold text-gray-900">{money(o.totalCents)}</p><p className="text-xs text-gray-400">{date(o.createdAt)}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${good?'bg-green-100 text-green-700':warn?'bg-red-100 text-red-700':'bg-gray-100 text-gray-600'}`}>{good?'Suivi actif':warn?'Suivi manquant':deliveries.find(x=>x[0]===o.deliveryStatus)?.[1]}</span><ChevronDown className={`h-5 w-5 text-gray-400 transition ${open===o.id?'rotate-180':''}`}/></button>
      {open===o.id&&<div className="border-t border-gray-100 p-4"><div className="grid gap-4 lg:grid-cols-2"><section className="space-y-3"><h3 className="font-extrabold">Traitement</h3><div className="grid gap-3 sm:grid-cols-2"><Field label="Préparation"><select className="input" value={o.fulfillmentStatus} disabled={!canEdit} onChange={e=>update(o.id,{fulfillmentStatus:e.target.value})}>{fulfilments.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></Field><Field label="Livraison"><select className="input" value={o.deliveryStatus} disabled={!canEdit} onChange={e=>update(o.id,{deliveryStatus:e.target.value})}>{deliveries.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></Field><Field label="Transporteur"><input className="input" value={o.carrier} disabled={!canEdit} onChange={e=>update(o.id,{carrier:e.target.value})} placeholder="Colissimo, DHL…"/></Field><Field label="Numéro de suivi"><input className={`input ${warn?'border-red-400 bg-red-50':''}`} value={o.trackingNumber} disabled={!canEdit} onChange={e=>update(o.id,{trackingNumber:e.target.value})} placeholder="Obligatoire pour expédier"/></Field></div><Field label="Lien de suivi"><input className="input" value={o.trackingUrl} disabled={!canEdit} onChange={e=>update(o.id,{trackingUrl:e.target.value})} placeholder="https://…"/></Field><Field label="Message visible par le client"><textarea className="input min-h-20" value={o.customerNote} disabled={!canEdit} onChange={e=>update(o.id,{customerNote:e.target.value})}/></Field><Field label="Note interne (équipe uniquement)"><textarea className="input min-h-20" value={o.internalNote} disabled={!canEdit} onChange={e=>update(o.id,{internalNote:e.target.value})}/></Field>{canEdit&&<button className="btn btn-primary" disabled={saving===o.id} onClick={()=>save(o)}><Save className="h-4 w-4"/>{saving===o.id?'Enregistrement…':'Enregistrer et notifier le client'}</button>}</section>
      <section><h3 className="font-extrabold">Client & livraison</h3><div className="mt-3 rounded-xl bg-gray-50 p-4 text-sm text-gray-700"><p className="font-bold">{o.customerName||'Client'}</p><p>{o.customerEmail}</p><p>{o.customerPhone}</p><p className="mt-2">{o.shippingAddress||[o.shippingLine1,o.shippingLine2,`${o.shippingPostalCode} ${o.shippingCity}`,o.shippingCountryCode].filter(Boolean).join(', ')||'Adresse à compléter'}</p><p className="mt-2 text-xs text-gray-500">{o.shippingMethod||'Livraison'} · {money(o.shippingCents)}</p></div><h3 className="mt-5 font-extrabold">Historique</h3><div className="mt-3 space-y-3">{o.events.length?o.events.map(e=><div key={e.id} className="border-l-2 border-blue-200 pl-3"><p className="text-sm font-bold text-gray-900">{e.title}</p><p className="text-xs text-gray-500">{e.detail}</p><p className="mt-1 text-[11px] text-gray-400">{date(e.createdAt)}{!e.visibleToCustomer?' · interne':''}</p></div>):<p className="text-sm text-gray-400">Aucun événement enregistré.</p>}</div></section></div></div>}
    </article>})}{!list.length&&<p className="rounded-2xl bg-white p-10 text-center text-gray-400 ring-1 ring-gray-200">Aucune commande dans ce filtre.</p>}</div></div>;
}
function Stat({icon,label,value,warn=false}:{icon:React.ReactNode;label:string;value:number;warn?:boolean}){return <div className={`flex items-center gap-3 rounded-2xl p-4 ring-1 ${warn&&value?'bg-red-50 ring-red-200':'bg-white ring-gray-200'}`}><span className={warn&&value?'text-red-600':'text-blue-600'}>{icon}</span><div><p className="text-2xl font-black text-gray-900">{value}</p><p className="text-xs font-semibold text-gray-500">{label}</p></div></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-sm font-bold text-gray-700">{label}<div className="mt-1">{children}</div></label>}
