'use client';
import { Suspense, useEffect, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { signIn } from 'next-auth/react';
import { CheckCircle2, ShieldCheck } from 'lucide-react';

function AcceptInvitation() {
  const params = useSearchParams(); const router = useRouter(); const token=params.get('token')||'';
  const [inv,setInv]=useState<any>(null); const [name,setName]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(true); const [done,setDone]=useState(false);
  useEffect(()=>{fetch(`/api/invitations/accept?token=${encodeURIComponent(token)}`).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setInv(d.invitation)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[token]);
  async function submit(e:React.FormEvent){e.preventDefault();setLoading(true);setError('');const r=await fetch('/api/invitations/accept',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,name,password})});const d=await r.json().catch(()=>({}));if(!r.ok){setError(d.error||'Acceptation impossible.');setLoading(false);return;}setDone(true);const login=await signIn('credentials',{redirect:false,email:d.email,password});if(login?.error){setError('Invitation acceptée. Connectez-vous maintenant.');setLoading(false);return;}router.replace('/dashboard/logistics');}
  return <main className="grid min-h-screen place-items-center bg-[#030611] bg-[radial-gradient(circle_at_top,#13265d_0,transparent_42%)] px-4 py-10 text-[#eef4ff]"><div className="w-full max-w-lg rounded-3xl border border-[#4cc9ff]/25 bg-[#070b1a]/90 p-6 shadow-[0_0_70px_rgba(47,107,255,.25)] sm:p-8"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-[#2f6bff]/20 text-[#72a8ff]"><ShieldCheck className="h-7 w-7"/></div>{loading&&!inv?<p className="mt-6 text-[#eef4ff]/70">Vérification de l’invitation…</p>:error&&!inv?<p className="mt-6 rounded-xl bg-red-500/15 p-4 font-semibold text-red-200">{error}</p>:<><p className="mt-6 text-xs font-black uppercase tracking-[.2em] text-[#72a8ff]">Invitation équipe</p><h1 className="mt-2 text-3xl font-black text-white">Rejoindre {inv.organizationName}</h1><p className="mt-2 text-[#eef4ff]/70">Accès attribué : <strong className="text-white">{inv.roleName}</strong></p>{done?<div className="mt-6 flex items-center gap-3 rounded-xl bg-green-500/15 p-4 text-green-200"><CheckCircle2/>Invitation acceptée, ouverture de votre espace…</div>:<form onSubmit={submit} className="mt-6 space-y-4">{!inv.existingAccount&&<label className="block text-sm font-bold text-[#eef4ff]/85">Votre nom<input className="mt-2 w-full rounded-xl border border-[#4cc9ff]/25 bg-white/10 px-4 py-3 text-white outline-none placeholder:text-white/40 focus:border-[#4cc9ff]" required value={name} onChange={e=>setName(e.target.value)} autoComplete="name"/></label>}<label className="block text-sm font-bold text-[#eef4ff]/85">{inv.existingAccount?'Votre mot de passe actuel':'Choisissez un mot de passe'}<input className="mt-2 w-full rounded-xl border border-[#4cc9ff]/25 bg-white/10 px-4 py-3 text-white outline-none placeholder:text-white/40 focus:border-[#4cc9ff]" type="password" required minLength={6} value={password} onChange={e=>setPassword(e.target.value)} autoComplete={inv.existingAccount?'current-password':'new-password'}/></label>{error&&<p className="rounded-xl bg-red-500/15 p-3 text-sm font-semibold text-red-200">{error}</p>}<button disabled={loading} className="w-full rounded-xl bg-[#2f6bff] px-5 py-3 font-black text-white shadow-[0_0_24px_rgba(47,107,255,.45)] disabled:opacity-50">{loading?'Validation…':'Accepter et ouvrir mon espace'}</button></form>}</>}</div></main>;
}
export default function AcceptInvitationPage(){return <Suspense><AcceptInvitation/></Suspense>}
